#!/usr/bin/env bash
# =============================================================================
# Generate Rancher Client ArgoCD configuration from import URL
# =============================================================================
# Usage: ./generate.sh <rancher-import-url> [environment]
#
# Example:
#   ./generate.sh "https://rancher.192.168.1.100.sslip.io/v3/import/TOKEN_c-CLUSTERID.yaml"
#   ./generate.sh "https://rancher.192.168.1.100.sslip.io/v3/import/TOKEN_c-CLUSTERID.yaml" prod
#
# Downloads the Rancher import manifest, extracts connection parameters,
# and generates config/<environment>.yaml for ArgoCD GitOps deployment.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_YAML="$(cd "${APP_DIR}/../.." && pwd)/config/config.yaml"
IMPORT_URL="${1:?Usage: $0 <rancher-import-url> [environment]}"
ENV="${2:-dev}"

# ---------------------------------------------------------------------------
# Read feature flags from global config.yaml
# ---------------------------------------------------------------------------
if [[ ! -f "$CONFIG_YAML" ]]; then
  echo "[ERROR] Global config not found: $CONFIG_YAML" >&2
  exit 1
fi

CNI_PRIMARY=$(yq '.cni.primary' "$CONFIG_YAML")
EGRESS_ENABLED=$(yq '.features.networkPolicy.egressPolicy.enabled' "$CONFIG_YAML")
KYVERNO_ENABLED=$(yq '.features.kyverno.enabled' "$CONFIG_YAML")
CIS_ENABLED=$(yq '.rke2.cis.enabled' "$CONFIG_YAML")

# Derive Helm feature flags
FEAT_CILIUM_EGRESS=false
if [[ "$CNI_PRIMARY" == "cilium" && "$EGRESS_ENABLED" == "true" ]]; then
  FEAT_CILIUM_EGRESS=true
fi
FEAT_KYVERNO=${KYVERNO_ENABLED:-false}
FEAT_CIS=${CIS_ENABLED:-false}

echo "[INFO] Feature flags (from $CONFIG_YAML):"
echo "  ciliumEgressPolicy:     $FEAT_CILIUM_EGRESS  (cni=$CNI_PRIMARY, egress=$EGRESS_ENABLED)"
echo "  kyvernoPolicyException: $FEAT_KYVERNO"
echo "  cisNamespace:           $FEAT_CIS"

echo "[INFO] Downloading Rancher import manifest..."
MANIFEST=$(curl --insecure -sfL "$IMPORT_URL")

# Extract Rancher server URL from the import URL
SERVER_URL=$(echo "$IMPORT_URL" | sed 's|/v3/import/.*||')
SERVER_IP=$(echo "$SERVER_URL" | sed -E 's|https?://[^.]*\.([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\..*|\1|')
INGRESS_IP_DOMAIN=$(echo "$SERVER_URL" | sed -E 's|https?://[^.]*\.[0-9.]+\.(.*)|\1|')

# Extract values from manifest
CA_CHECKSUM=$(echo "$MANIFEST" | grep -oP 'value:\s*"\K[a-f0-9]{64}' | head -1)
SERVER_VERSION=$(echo "$MANIFEST" | grep -A1 'CATTLE_SERVER_VERSION' | tail -1 | awk '{print $NF}' | tr -d '"')
INSTALL_UUID=$(echo "$MANIFEST" | grep -A1 'CATTLE_INSTALL_UUID' | tail -1 | awk '{print $NF}' | tr -d '"')
CREDENTIAL_NAME=$(echo "$MANIFEST" | grep -A1 'CATTLE_CREDENTIAL_NAME' | tail -1 | awk '{print $NF}' | tr -d '"')
AGENT_IMAGE=$(echo "$MANIFEST" | grep 'image:' | grep rancher | head -1 | awk '{print $2}' | sed 's|:.*||')

# Extract credential secret data
CRED_URL=$(echo "$MANIFEST" | awk '/kind: Secret/{found=1} found && /^\s*url:/{print $2; exit}' | tr -d '"')
CRED_TOKEN=$(echo "$MANIFEST" | awk '/kind: Secret/{found=1} found && /^\s*token:/{print $2; exit}' | tr -d '"')

echo "[INFO] Extracted configuration:"
echo "  Server URL:       $SERVER_URL"
echo "  Server IP:        $SERVER_IP"
echo "  CA Checksum:      $CA_CHECKSUM"
echo "  Server Version:   $SERVER_VERSION"
echo "  Install UUID:     $INSTALL_UUID"
echo "  Credential Name:  $CREDENTIAL_NAME"
echo "  Agent Image:      $AGENT_IMAGE"
echo "  Ingress Domain:   $INGRESS_IP_DOMAIN"

CONFIG_FILE="${APP_DIR}/config/${ENV}.yaml"
cat > "$CONFIG_FILE" <<EOF
---
# =============================================================================
# Rancher Client - ${ENV^} Environment Configuration
# =============================================================================
# Generated by: ./generate.sh <rancher-import-url>

environment: ${ENV}
appName: rancher-client

rancherClient:
  server:
    url: "${SERVER_URL}"
    ip: "${SERVER_IP}"
    caChecksum: "${CA_CHECKSUM}"
    version: "${SERVER_VERSION}"
    installUUID: "${INSTALL_UUID}"
    ingressIpDomain: "${INGRESS_IP_DOMAIN}"
  credentials:
    secretName: "${CREDENTIAL_NAME}"
    url: "${CRED_URL}"
    token: "${CRED_TOKEN}"
  agent:
    image: "${AGENT_IMAGE}"

features:
  kyvernoPolicyException: ${FEAT_KYVERNO}
  ciliumEgressPolicy: ${FEAT_CILIUM_EGRESS}
  cisNamespace: ${FEAT_CIS}

syncPolicy:
  syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
  automated:
    enabled: true
    prune: true
    selfHeal: true
EOF

echo "[OK] Configuration written to ${CONFIG_FILE}"
