{
 "title": "ArgoCD / Operational / Overview",
 "description": "A dashboard that monitors ArgoCD with a focus on the operational. It is created using the [argo-cd-mixin](https://github.com/adinhodovic/argo-cd-mixin).",
 "tags": [
  "ci/cd",
  "argo-cd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": "in-cluster" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info, namespace)"
   },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "kubernetes_cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\"}, project)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_cluster_info{\n    namespace=~'$namespace',\n    job=~'$job'\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  count(\n    argocd_app_info{\n        namespace=~'$namespace',\n      job=~'$job'\n    }\n  )\n  by (repo)\n)\n"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (health_status)\n",
     "legendFormat": "{{ health_status }}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (sync_status)\n",
     "legendFormat": "{{ sync_status }}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, name, health_status, sync_status)\n"
    }
   ]
  },
  { "title": "Sync Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, dest_server, project, name)\n",
     "legendFormat": "{{ project }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n        phase=~\"Error|Failed\"\n      }[$__rate_interval]\n    )\n  )\n) by (job, dest_server, project, name, phase)\n",
     "legendFormat": "{{ project }}/{{ name }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recociliation Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_app_reconcile_count{\n            namespace=~'$namespace',\n        job=~'$job',\n        dest_server=~'$kubernetes_cluster'\n      }[$__rate_interval]\n    )\n  )\n) by (namespace, job)\n",
       "legendFormat": "{{ namespace }}/{{ job }}"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    argocd_app_reconcile_bucket{\n        namespace=~'$namespace',\n      job=~'$job',\n      dest_server=~'$kubernetes_cluster'\n    }[$__rate_interval]\n  )\n) by (le)\n",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "K8s API Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_app_k8s_request_total{\n            namespace=~'$namespace',\n        job=~'$job',\n        project=~'$project'\n      }[$__rate_interval]\n    )\n  )\n) by (job, verb, resource_kind)\n",
       "legendFormat": "{{ verb }} {{ resource_kind }}"
      }
     ]
    },
    {
     "title": "Pending Kubectl Runs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_kubectl_exec_pending{\n    namespace=~'$namespace',\n    job=~'$job'\n  }\n) by (job, command)\n",
       "legendFormat": "{{ command }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_cluster_api_resource_objects{\n    namespace=~'$namespace',\n    job=~'$job',\n    server=~'$kubernetes_cluster'\n  }\n) by (namespace, job, server)\n",
       "legendFormat": "{{ server }}"
      }
     ]
    },
    {
     "title": "API Resources",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_cluster_api_resources{\n    namespace=~'$namespace',\n    job=~'$job',\n    server=~'$kubernetes_cluster'\n  }\n) by (namespace, job, server)\n",
       "legendFormat": "{{ server }}"
      }
     ]
    },
    {
     "title": "Cluster Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    argocd_cluster_events_total{\n      namespace=~'$namespace',\n      job=~'$job',\n      server=~'$kubernetes_cluster'\n    }[$__rate_interval]\n  )\n) by (namespace, job, server)\n",
       "legendFormat": "{{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repo Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Requests (ls-remote)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    argocd_git_request_total{\n        namespace=~'$namespace',\n      job=~'$job',\n      request_type=\"ls-remote\"\n    }[$__rate_interval]\n  )\n) by (namespace, job, repo)\n",
       "legendFormat": "{{ namespace }} - {{ repo }}"
      }
     ]
    },
    {
     "title": "Git Requests (checkout)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    argocd_git_request_total{\n        namespace=~'$namespace',\n      job=~'$job',\n      request_type=\"fetch\"\n    }[$__rate_interval]\n  )\n) by (namespace, job, repo)\n",
       "legendFormat": "{{ namespace }} - {{ repo }}"
      }
     ]
    },
    {
     "title": "Git Fetch Performance",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    argocd_git_request_duration_seconds_bucket{\n        namespace=~'$namespace',\n      job=~'$job',\n      request_type=\"fetch\"\n    }[$__rate_interval]\n  )\n) by (le)\n",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Git Ls-remote Performance",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    argocd_git_request_duration_seconds_bucket{\n        namespace=~'$namespace',\n      job=~'$job',\n      request_type=\"ls-remote\"\n    }[$__rate_interval]\n  )\n) by (le)\n",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}