apiVersion: ENC[AES256_GCM,data:FIs=,iv:vY6BJUU00c8Xjvm7ftOPOdWy0is4eLbxZdtiPCgFpLI=,tag:D2MPJxRFc7o8sFK4Uz4+Pw==,type:str]
kind: ENC[AES256_GCM,data:zMYxjkYx,iv:dv3VJEQ//YmtkAeXelgOn4c5WcLYrs6hsxQzZIttMmo=,tag:qW4Y8iqCWYXCQgPQMlmlfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C5Zd0ZHe/NekAhyf7rMmKjnzdkjWLW29Ig==,iv:1nBAYt6zgKz2v0XLJuID9ngTTZbyQsEtNmcZZaeGkwk=,tag:u00QTjayYQElsboeNQGurA==,type:str]
    namespace: ENC[AES256_GCM,data:VUc4RZuU4TfhjmXJ,iv:s5/P6X4AT7UvegEIii4UhlsBHXy6JA0tYR1PgfTSVjc=,tag:kY44onTY4WZFBtvGZtUAjg==,type:str]
type: ENC[AES256_GCM,data:ayPXNP8M,iv:lZ0miDR/dS8Dw4M5VdEvn1IvdSMS6WAKLYNsSuUDDeg=,tag:ZwmvsyUC040H98K9Wid6vA==,type:str]
stringData:
    redis-password: ENC[AES256_GCM,data:4lBkfnxEwIo6DRTjUhdYDFPmbww8wMspq9NWCLHdqg==,iv:WgznD+wYHEYYSE61Mm2/SGhWU9Yhg/Q2FjJq+RJbAIo=,tag:fisA41u1k+JMWFe2FQuLNA==,type:str]
sops:
    age:
        - recipient: age1are2lwem3jtdp3z06xgj5ljvg2xn0rs6yn29x643v3phzkml7clqunt3s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd0RiTmhORGRCbHdDc3U1
            SHBRWXpIVGV0REJPb1hQcjRvNWhjVk1qSlNvClN0dncwOFJCUWVmbE1YZzE5Qnlv
            SVFtUTJFbDlEaE9QaitqelAzWnZ2ZXcKLS0tIDNBUHNieWd1ckFyQTlqaVRPWit2
            QmFzSXg4cmhQY0ZxcVhYWDFpYXNaVUEKWxgaiOJtDC5ph1NP+BIXxC1gkdBO90LD
            c2gdzU2IyZoPDBZGPnIhvRDHRUvmP7SYvObWNUB4mps8pYZkX0TdFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T17:27:28Z"
    mac: ENC[AES256_GCM,data:XOwj1H/2eTOiKu5Lev7b9XTluOpmYennc+vO9rzfTXTrxYzCGspW6DJbQvclIifHvVmLC4KmqHPGqWUaj2nD4+zelzLzTJ+hKeVEk3lgaofZoJjt+5TG6ugCAjKMURLJnyrUR85PXpcqhXv5BzHRtUE7U9O5Q450ajCZeh7o14s=,iv:moCOMDLfFigGcbOKQcB44+64gPS2tvVS2RGrLE4TJKw=,tag:H/95oPUvS97LGmoe20na7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
