#ENC[AES256_GCM,data:GPCmr6wr0dlO/W2INe0lmNcdBw7KluQ3n6S3gFDPO45UEIS/CKitIpD4/el8p7DFdmzlPhH1bf+Z+aVpc0uXkW/7FjRMpK49Pdkl,iv:phboeoTLm0SBe6wudoV9ZDAdyy+pvDBMLiciha4l/2g=,tag:P12k3AiQbJe8/ptkUjeX4g==,type:comment]
#ENC[AES256_GCM,data:g3tAhlBt5F+zM6rQ6HlniOUe2Z/Nac4F7qRlHgvEFxzJ3IdHcSMhQhpX3W2OrDXCBp4Tg4CVcgXvNLlpUnUpZw==,iv:goI7u8MaaOTgumwpKCjBQx74LUCc6+x+MOX+6U2xjvc=,tag:ZiAoQq65QOfrj3eLAotGbA==,type:comment]
#ENC[AES256_GCM,data:BfC2eDqyq8uwnBMKhvjM79b2zCBmcpgpykFjHKmNfIqxj3uzsqSnBuMDS+oL4h4fkHRNyNoFoE8+TRDcfq8F+FU9TFqK5NaJyg==,iv:LVTIP1GVxSczHgwO7b0UzN/YPHwZlcchvb/oXTK/w40=,tag:aa5medXAgdhLDKaqS5L9Vg==,type:comment]
apiVersion: ENC[AES256_GCM,data:iOo=,iv:/KwiiOpOY4hEGBdvv6vLXmXlde/qKOntaOXc8pFX3m0=,tag:ugr3iUvbTANAM6sVHqWc4A==,type:str]
kind: ENC[AES256_GCM,data:7ZsB0KBw,iv:a8rPHckWotmrpSbKbVKYxmwaTJOvkVKsOApfDbSbsJ0=,tag:tJrTPohXIjEKbpp2L030/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EkmmpGC4jQGkXveL8F1SCwvmipAnzgo=,iv:r8IdLjdw/I23oK4GbZCvgZfFLCaNNO6f3+Z2EpiUOdo=,tag:d1SMkk/BYN9EX9V16vaucw==,type:str]
    namespace: ENC[AES256_GCM,data:6VSe6XeM,iv:yjeNyPr1a1ee8S/7XUg85+Lpc582DV/xbN78dtZ+OAE=,tag:xGA8t8VECzOxc7gQng/CZw==,type:str]
type: ENC[AES256_GCM,data:ImF18eKG,iv:ZrgbITY/V78tyO/ieKeJGJrjzE0+7BRb9h3ydzy1mIY=,tag:EgR+TzcQMYvHnIn9oHgVZg==,type:str]
stringData:
    repository-password: ENC[AES256_GCM,data:lAuw3vZEcLI01FqBboS/Z6RVyqvGxa/rnBOcryMuJj2OzItAPDlODwaioT4=,iv:2+JclHvO4nnZyot53mfFQXA327adqwUFGOdrs2pXTqo=,tag:btiNHvHyzkaz/jqWHvmHdQ==,type:str]
sops:
    age:
        - recipient: age1are2lwem3jtdp3z06xgj5ljvg2xn0rs6yn29x643v3phzkml7clqunt3s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUEo0Y3E0ZVFLYllObWZr
            NjJnWVZ6d0FKYXVONTBranJFYUNicllsSVZrCi9Hd0xMMy9NZHVMSHl3dzBmQ0w5
            OXQ5eHdWYTZUWlRNYlQ1ZFFrUHJSLzAKLS0tIHY5czlaUlBMSkZDYzM3R0RnYUUw
            NTBhN09xUWhJWGhwMTRUbGtGcWhzQ3cKXdak+/x6PDKatw133ac8ECTPYrsvmDXS
            u8UyAXekDl8xzUpKskX/BuwXcrLNJ812BBqKAutmXid2PZl3NY+i0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T13:38:49Z"
    mac: ENC[AES256_GCM,data:ktJIQhKNUGkaQ8Ir6l5028E8eR2b2Rr0hvBsFKOfv3wCzuA6ftKGn5ipJiK9bhnqVUv1N5uXu5G5OZ6wR/3AcRJTF0hzs23qE+nrD3bAaF3ohdWraMBqh/RPXsmIDSmYl7ELuUpLwUI+nJIEXmigns26ESRa53Fd6Py6uYah0oE=,iv:ach4vDXjV7uKNSDDc/Jw0BsTPMNpLmQpn5I7RGm5qYY=,tag:Sk9k3rLe+XJN+LCGCx0Ghg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
