---
apiVersion: v1
kind: Service
metadata:
  name: kubevirt-metrics
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: kubevirt-metrics
spec:
  ports:
  - name: metrics
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    kubevirt.io: virt-operator
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kubevirt-api-metrics
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: kubevirt-metrics
spec:
  ports:
  - name: metrics
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    kubevirt.io: virt-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kubevirt-controller-metrics
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: kubevirt-metrics
spec:
  ports:
  - name: metrics
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    kubevirt.io: virt-controller
  type: ClusterIP
