# -*- mode: ruby -*-
# vi: set ft=ruby :

# virsh net-list --all
# virsh net-update vagrant-libvirt add-last ip-dhcp-host '<host mac="52:54:00:00:00:01" ip="192.168.122.100"/>' --live --config --parent-index 0
# virsh net-dumpxml vagrant-libvirt

# https://www.rubydoc.info/gems/vagrant-libvirt/0.0.28

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

### VARS ###
# Management node
management = false
management_memory = 8192
management_cpu = 4
management_disk = 20

# Only one node
masters = 1
workers = 0
master_cpu = 16
master_memory = 32768
master_disk = 100

# Masters + workers on the same node (no additionnal worker)
# masters = 3
# workers = 0
# master_cpu = 8
# master_memory = 16384
# master_disk = 50

# Masters + workers
# masters = 3
# workers = 3
# master_cpu = 4
# master_memory = 8192
# master_disk = 20
# worker_cpu = 8
# worker_memory = 8192
# worker_disk = 50

Vagrant.configure("2") do |config|
  if management
    config.vm.define "k8s-management" do |management|
      management.vm.box = "debian/bookworm64"
      management.vm.box_check_update = true
      # management.vm.box_check_update = false
      management.vm.hostname = "k8s-management"
      # management.vm.network "public_network", ip: "192.168.122.10"
      management.vm.network "private_network", ip: "192.168.122.10"
      management.vm.provider "libvirt" do |domain|
        domain.default_prefix = ""
        domain.cpus = management_cpu
        domain.memory = management_memory
        domain.machine_virtual_size = management_disk
        domain.keymap = "fr"
      end
      management.vm.provision "shell", path: "git/rke2/install_common.sh", args: ["management"]
      management.vm.provision "shell", path: "git/rke2/install_management.sh"
    end
  end

  (1..masters).each do |i|
    config.vm.define "k8s-m#{i}" do |master|
      master.vm.box = "debian/bookworm64"
      master.vm.box_check_update = true
      # master.vm.box_check_update = false
      master.vm.hostname = "k8s-m#{i}"
      master.vm.network "private_network", ip: "192.168.122.1#{i}"
      # master.vm.network "public_network", ip: "192.168.122.1#{i}", dev: "wlp0s20f3"
      master.vm.provider "libvirt" do |domain|
        #if i == 1
        #  domain.management_network_mac = "52:54:00:00:00:01"
        #end
        domain.default_prefix = ""
        domain.cpus = master_cpu
        domain.memory = master_memory
        domain.machine_virtual_size = master_disk
        domain.keymap = "fr"
      end

      if i == 1
        master.vm.provision "shell", inline: <<-SHELL
          rm -f /vagrant/{k8s-token,ip_master,kube.config}
          ip a show dev eth0 | egrep -w inet | awk '{ print $2 }' | awk -F'/' '{ print $1 }' > /vagrant/ip_master
        SHELL
      end

      if i > 1
        master.vm.provision "shell", inline: <<-SHELL
          echo "Waiting 1st master node to finish his installation"
          while true
          do
            sleep 5
            test -f /vagrant/k8s-token && break
          done
          echo "1st master node has finished his installation. This node can continue his installation"
          mkdir -p /etc/rancher/rke2
          echo "server: https://$(cat /vagrant/ip_master):9345" >> /etc/rancher/rke2/config.yaml
          echo "token: $(cat /vagrant/k8s-token)" >> /etc/rancher/rke2/config.yaml
        SHELL
      end

      if masters > 1 and workers > 0
        master.vm.provision "shell", inline: <<-SHELL
          echo "node-taint:" >> /etc/rancher/rke2/config.yaml
          echo '  - "CriticalAddonsOnly=true:NoExecute"' >> /etc/rancher/rke2/config.yaml
        SHELL
      end

      master.vm.provision "shell", path: "git/rke2/install_common.sh"
      master.vm.provision "shell", path: "git/rke2/install_master.sh"

      if i == 1
        master.vm.provision "shell", inline: <<-SHELL
          if test -f /etc/rancher/rke2/rke2.yaml
          then
            cp /etc/rancher/rke2/rke2.yaml /vagrant/kube.config
            sed -i "s@127.0.0.1@$(cat /vagrant/ip_master)@g" /vagrant/kube.config
            # sed -i "s@127.0.0.1@k8s-api.gigix@g" /vagrant/kube.config
            cp /var/lib/rancher/rke2/server/node-token /vagrant/k8s-token
          fi
        SHELL
      end
    end
  end

  (1..workers).each do |i|
    config.vm.define "k8s-w#{i}" do |worker|
      worker.vm.box = "debian/bookworm64"
      worker.vm.box_check_update = true
      # worker.vm.box_check_update = false
      worker.vm.hostname = "k8s-w#{i}"
      # worker.vm.network "public_network", ip: "192.168.122.10#{i}"
      worker.vm.network "private_network", ip: "192.168.122.10#{i}"
      worker.vm.provider "libvirt" do |domain|
        domain.default_prefix = ""
        domain.cpus = worker_cpu
        domain.memory = worker_memory
        domain.machine_virtual_size = worker_disk
        domain.keymap = "fr"
      end
      worker.vm.provision "shell", path: "git/rke2/install_common.sh"
      worker.vm.provision "shell", path: "git/rke2/install_worker.sh"
    end
  end
end
