{
 "title": "Ceph Application - Overview",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_health_status, job)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(ceph_pool_metadata{job=\"$cluster\"},application)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(ceph_pool_metadata{application=~\"$application\", job=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application (${application:csv})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes{job=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS (${application:csv} - $pool)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_pool_rd{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\"})",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "Application Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 } },
  {
   "title": "Capacity Used",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (ceph_pool_stored{job=~\"$cluster\",} *\n  on(pool_id) group_left(instance, name, application) ceph_pool_metadata{job=~\"$cluster\",application=~\"(.*Block.*)|(.*Filesystem.*)|(.*Object.*)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (${application:csv} - $pool)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$cluster\",application=~\"$application\", name=~\"$pool\"})",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{job=~\"$cluster\",}*\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\",application=~\"$application\", name=~\"$pool\"}\n   - \n   (ceph_pool_stored{job=~\"$cluster\",}  *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\",application=~\"$application\", name=~\"$pool\"})) > 0 \n  or\n  \n(ceph_pool_max_avail{job=~\"$cluster\",} *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\",application=~\"$application\", name=~\"$pool\"})",
     "legendFormat": "B"
    },
    {
     "expr": "(ceph_pool_stored{job=~\"$cluster\",} *on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\"})\n  /\n  (((ceph_pool_quota_bytes{job=~\"$cluster\"} > 0) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\", name=~\"$pool\", application=~\"$application\"}) or \n((ceph_pool_max_avail{job=~\"$cluster\"} \n+\nceph_pool_stored{job=~\"$cluster\", }) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\", application=~\"$application\"}))",
     "legendFormat": "D"
    },
    {
     "expr": "rate(ceph_pool_rd{job=~\"$cluster\", }[$__rate_interval]) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"}\n  + rate(ceph_pool_wr{job=~\"$cluster\", }[$__rate_interval]) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"}\n",
     "legendFormat": "G"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{job=~\"$cluster\", }[$__rate_interval]) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"} +\n  rate(ceph_pool_wr_bytes{job=~\"$cluster\", }[$__rate_interval]) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"}\n",
     "legendFormat": "H"
    },
    {
     "expr": "ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"}",
     "legendFormat": "I"
    },
    {
     "expr": "ceph_pool_stored{job=~\"$cluster\", } * on(pool_id) group_left ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"}",
     "legendFormat": "J"
    },
    {
     "expr": "ceph_pool_quota_bytes{job=~\"$cluster\",} *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\",name=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "((ceph_pool_quota_bytes{job=~\"$cluster\"}) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\", application=~\"$application\", name=~\"$pool\"})",
     "legendFormat": "N"
    }
   ]
  },
  {
   "title": "Total used capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_pool_stored{job=~\"$cluster\",} *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_pool_wr{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\"}",
     "legendFormat": "{{name}} - Writes"
    },
    {
     "expr": "rate(ceph_pool_rd{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\",name=~\"$pool\"}",
     "legendFormat": "{{name}} - Reads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_pool_wr_bytes{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\", name=~\"$pool\"}",
     "legendFormat": "{{name}} - Writes"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{job=~\"$cluster\",}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\", name=~\"$pool\"}",
     "legendFormat": "{{name}} - Reads"
    }
   ]
  },
  {
   "title": "Total objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_pool_objects{job=~\"$cluster\",} *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$cluster\", name=~\"$pool\"}\n",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}