{
 "title": "Ceph OSD - Device Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, job)"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_metadata{job=~\"$cluster\", }, ceph_daemon)"
   },
   {
    "name": "osd_host",
    "label": "OSD Host",
    "query": "label_values(ceph_osd_metadata{ceph_daemon=~\"$osd\", job=~\"$cluster\"}, hostname)"
   },
   {
    "name": "node_instance",
    "label": "Node Instance",
    "query": "label_values(node_uname_info{nodename=~\"$osd_host\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$osd Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"}[$__rate_interval]) / on (ceph_daemon, job) rate(ceph_osd_op_r_latency_count{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"}[$__rate_interval]) / on (ceph_daemon, job) rate(ceph_osd_op_w_latency_count{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "$osd R/W IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\", }[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_osd_op_w{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\", }[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "$osd R/W Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_out_bytes{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\", }[$__rate_interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(ceph_osd_op_w_in_bytes{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\", }[$__rate_interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  { "title": "Physical Device Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Physical Device Latency for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_read_time_seconds_total{instance=~\"$node_instance\"}[$__rate_interval]) /\n  rate(node_disk_reads_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{instance}}/{{device}} Reads"
    },
    {
     "expr": "(\n  rate(node_disk_write_time_seconds_total{instance=~\"$node_instance\"}[$__rate_interval]) /\n  rate(node_disk_writes_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{instance}}/{{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device R/W IOPS for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_writes_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}} on {{instance}} Writes"
    },
    {
     "expr": "(\n  rate(node_disk_reads_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}} on {{instance}} Reads"
    }
   ]
  },
  {
   "title": "Physical Device R/W Bytes for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_read_bytes_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{instance}} {{device}} Reads"
    },
    {
     "expr": "(\n  rate(node_disk_written_bytes_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{instance}} {{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device Util% for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_io_time_seconds_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", job=\"rook-ceph-mgr\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}} on {{instance}}"
    }
   ]
  }
 ]
}