{
 "title": "NeuVector Dashboard",
 "tags": [
  "neuvector",
  "security"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_hosts" }
   ]
  },
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_controllers" }
   ]
  },
  {
   "title": "Enforcers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_enforcers" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_pods" }
   ]
  },
  {
   "title": "Disconnected Enforcers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_summary_disconnectedEnforcers"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(nv_conversation_bytes[1m]))*60",
     "legendFormat": "bytes per minute"
    }
   ]
  },
  {
   "title": "Allowed Admissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_admission_allowed" }
   ]
  },
  {
   "title": "Denied Admissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_admission_denied" }
   ]
  },
  {
   "title": "CVEDB Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_cvedbVersion" }
   ]
  },
  {
   "title": "CVEDB Create Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_cvedbTime" }
   ]
  },
  {
   "title": "CPU Usage (Controller & Enforcer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "nv_enforcer_cpu", "legendFormat": "Enforcer: {{display}}" },
    { "expr": "nv_controller_cpu", "legendFormat": "Controller: {{display}}" }
   ]
  },
  {
   "title": "Memory Usage (Controller & Enforcer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nv_enforcer_memory", "legendFormat": "Enforcer: {{display}}" },
    { "expr": "nv_controller_memory", "legendFormat": "Controller: {{display}}" }
   ]
  },
  {
   "title": "Service Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(nv_container_vulnerabilityHigh) by (service)"
    },
    {
     "expr": "sum(nv_container_vulnerabilityMedium) by (service)"
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(nv_image_vulnerabilityHigh) by (name)"
    },
    {
     "expr": "sum(nv_image_vulnerabilityMedium) by (name)"
    }
   ]
  },
  {
   "title": "Security Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "nv_log_events" }
   ]
  }
 ]
}