---
# =============================================================================
# KubeVirt - Dev Environment Configuration
# =============================================================================

environment: dev
appName: kubevirt

kubevirt:
  manager:
    version: "0.5.2"
    appVersion: "1.5.4"
  liveMigration:
    bandwidthPerMigration: "64Mi"
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  automated:
    enabled: true
    prune: true
    selfHeal: true
