#ENC[AES256_GCM,data:w50UlBKp1L22xnzrSzN3LdelKtbF3uWkp6f7n8QoLfDPJ4SAc9ywxvBzuq+TE636+GY=,iv:x/biQzCBb5Q2PLJXdoYnhT0NLvxpV7ODqYEv36bS/Y0=,tag:9bJkJJDTBhACbL3kY3mIhw==,type:comment]
apiVersion: ENC[AES256_GCM,data:VR8=,iv:WfKkyYOMC6Vw2PJ3jjkvm2ZitqMAhs1aeMaxpXw0H/E=,tag:4/hn3wquKkCRHOiPVhwAfA==,type:str]
kind: ENC[AES256_GCM,data:xMvOUZcQ,iv:WMwvX6YyaeUtfFn4YYGP4Ho3l3J7tdz4fi9nzpUCqDo=,tag:STG+VIaEjO1UVrDBXun9Zw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4gMDDSpqw3uaJ0vAraivNNUV7RHR/0U=,iv:4Pc2qWJ700i804ulDB4vtdonTb5qytGyV8h4cuugbJk=,tag:A29HUli1ibD2HQaw7TwDdg==,type:str]
    namespace: ENC[AES256_GCM,data:0+wShB8VfPOQ,iv:KJQ9B+xXc+Y21f1DISNlUkPQbrf2zCnPyTkWBXNAf+I=,tag:X9eKe8/P4JuszFxk9z0tNQ==,type:str]
type: ENC[AES256_GCM,data:9l2i9bLj,iv:jvrqiSbEg2kf/b0H1h5PMtPZHV5RsToIIIC4mTNd5mU=,tag:rFi4TWBYzmFrH42ji50RIg==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:BPnlNpPT,iv:I+Px+9paZGN7VOLqEPflx48wMfJH3HyOAo56RuxxJV8=,tag:iOV7BNrk7STj1R3+wZIJsg==,type:str]
    client-secret: ENC[AES256_GCM,data:CpV096PrHC1i5J52wKCj7o+u8fzjVOgvcv7a,iv:xNvrDJUiN5wwOcQESmFiJnWb19sUaPLkNThEnuTwi9Y=,tag:aKEiWCU8CmDutplriKIL1A==,type:str]
sops:
    age:
        - recipient: age1na7yj6ktcusnpwed94fzst2acl9qguznktc3dwvhf3wap8u2g4ysg5t9qt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZWlDUXlhajJ5a2JIcnpy
            aHd6dzdmdVFjbVdkYXlaRk5tMVQvR2hNcjN3Cm9HMVV1YjFBQ1VGeE8rVW5ZZUha
            TVA4MlpEclZtdGd6ckQxU2duMFpoOVEKLS0tIG9HbWJqMGdsRG1wMStLajdnQ0Vv
            M1NpQjlET01PZjBySzdreWJycldQaWMKYa4poMf64cE94CvfUhNsoHpTDfKeeiTd
            MBlvl4Njl3GRukPY3KYUHMzFG4bBVGnO/Xotk9OmpalbwF/xbMvDug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T10:09:46Z"
    mac: ENC[AES256_GCM,data:kgMy5o+QFW+u7lkBk+HQp+gXPBqor0wvQNhAb/FgGNNka+DPBMgG9m9hS96T3VNk1JAA4rKCJG/CvGd5BwxiySt18jIwmPXpSGfAZAsnGPzHDBjsXldj+EKeb8O2C71ZBH9xRGpNX6y83lW4Uhjf/ZiPbiagH7ly0QGbpePBYCM=,iv:Nfq7FErFLMOdqb8luM+XKTPCS310/dRHdHW1a1Td4+4=,tag:IF6sSR870X9PYsto7TyHaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:wwh30pgI0FBn9Hb9C1AMTX6Legq98KFn1llSwmFf/HkAqDvqrwM84Ly+udlw8YfdJ1DDpBQ5TZHsIsAN7leOjJlD4vM=,iv:FANP8tDUPxLeraiCUoWkaW86z6NGV00XRABjFyw+cY8=,tag:8fBgHKaRj6lAH9TNixJuzQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:Foc=,iv:OBKNJpTlsO1VowV00DvDW/9kGjliP6nGEQlyOkWxhu0=,tag:3UcYh0EIoDAi5Xt2wM78PQ==,type:str]
kind: ENC[AES256_GCM,data:8x4a8NT8,iv:CoYnHknt3cM594DEbvz+/u5hnFTrYkTt6PqFqmZyP18=,tag:/7rvfWBgnr/xelFpFHmIiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h23quF7hU36ojTnXHfjBc4KzgvxCG2Y=,iv:IkfcT45IZcyeLaRPOvGnTuWpCEzav8XCUGHmv7Fgq7o=,tag:yYBz/6XbXAuPdbXIFH/3kw==,type:str]
    namespace: ENC[AES256_GCM,data:U0tkfpxzGzk=,iv:dnURJciyBhKOp71Q25jmZJh2SeymEL+dEpT94NpeLpo=,tag:Q9WA+XytD9XF1KETDqYHdQ==,type:str]
type: ENC[AES256_GCM,data:XB/qO8NB,iv:tOBUY+GldeTB9HG2AOuwPCzHVH8s3wR9OF9XaMmYjA8=,tag:hRP3Th5b0GhL0VbcGaAqTQ==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:TTVe/rd2,iv:o/bypf4JfZu2U7cq2I3esFTAuX5htzpxa/Y8lSjwbVU=,tag:C31ySUGdjJYEJAvMEa4bqQ==,type:str]
    client-secret: ENC[AES256_GCM,data:x/ONfODA3PK951HDQch5I8pgNfrc7qUUifls,iv:PehA+tWufy8h1oj6fpy4cjYCBZpMAoC7iuwYj1ADqRI=,tag:qVPo2VuLlbCvngaZ3WQOWQ==,type:str]
sops:
    age:
        - recipient: age1na7yj6ktcusnpwed94fzst2acl9qguznktc3dwvhf3wap8u2g4ysg5t9qt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZWlDUXlhajJ5a2JIcnpy
            aHd6dzdmdVFjbVdkYXlaRk5tMVQvR2hNcjN3Cm9HMVV1YjFBQ1VGeE8rVW5ZZUha
            TVA4MlpEclZtdGd6ckQxU2duMFpoOVEKLS0tIG9HbWJqMGdsRG1wMStLajdnQ0Vv
            M1NpQjlET01PZjBySzdreWJycldQaWMKYa4poMf64cE94CvfUhNsoHpTDfKeeiTd
            MBlvl4Njl3GRukPY3KYUHMzFG4bBVGnO/Xotk9OmpalbwF/xbMvDug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T10:09:46Z"
    mac: ENC[AES256_GCM,data:kgMy5o+QFW+u7lkBk+HQp+gXPBqor0wvQNhAb/FgGNNka+DPBMgG9m9hS96T3VNk1JAA4rKCJG/CvGd5BwxiySt18jIwmPXpSGfAZAsnGPzHDBjsXldj+EKeb8O2C71ZBH9xRGpNX6y83lW4Uhjf/ZiPbiagH7ly0QGbpePBYCM=,iv:Nfq7FErFLMOdqb8luM+XKTPCS310/dRHdHW1a1Td4+4=,tag:IF6sSR870X9PYsto7TyHaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
