{
 "title": "Ceph Host - Details",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, job)"
   },
   {
    "name": "ceph_hosts",
    "query": "label_values({__name__=~\"ceph_.+_metadata\", job=~\"$cluster\", }, hostname)"
   },
   {
    "name": "node_instance",
    "label": "Node Instance",
    "query": "label_values(node_uname_info{nodename=~\"$ceph_hosts\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$ceph_hosts System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (ceph_daemon) (ceph_osd_metadata{job=~\"$cluster\",  hostname=~\"$ceph_hosts\"}))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (mode) (\n  rate(node_cpu{instance=~\"$node_instance\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[$__rate_interval]) or\n  rate(node_cpu_seconds_total{instance=~\"$node_instance\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[$__rate_interval])\n) / (\n  scalar(\n    sum(rate(node_cpu{instance=~\"$node_instance\"}[$__rate_interval]) or\n    rate(node_cpu_seconds_total{instance=~\"$node_instance\"}[$__rate_interval]))\n  ) * 100\n)\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree{instance=~\"$node_instance\"} or\nnode_memory_MemFree_bytes{instance=~\"$node_instance\"}\n",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$node_instance\"} or\nnode_memory_MemTotal_bytes{instance=~\"$node_instance\"}\n",
     "legendFormat": "total"
    },
    {
     "expr": "(\n  node_memory_Cached{instance=~\"$node_instance\"} or\n  node_memory_Cached_bytes{instance=~\"$node_instance\"}\n) + (\n  node_memory_Buffers{instance=~\"$node_instance\"} or\n  node_memory_Buffers_bytes{instance=~\"$node_instance\"}\n) + (\n  node_memory_Slab{instance=~\"$node_instance\"} or\n  node_memory_Slab_bytes{instance=~\"$node_instance\"}\n)\n",
     "legendFormat": "buffers/cache"
    },
    {
     "expr": "(\n  node_memory_MemTotal{instance=~\"$node_instance\"} or\n  node_memory_MemTotal_bytes{instance=~\"$node_instance\"}\n) - (\n  (\n    node_memory_MemFree{instance=~\"$node_instance\"} or\n    node_memory_MemFree_bytes{instance=~\"$node_instance\"}\n  ) + (\n    node_memory_Cached{instance=~\"$node_instance\"} or\n    node_memory_Cached_bytes{instance=~\"$node_instance\"}\n  ) + (\n    node_memory_Buffers{instance=~\"$node_instance\"} or\n    node_memory_Buffers_bytes{instance=~\"$node_instance\"}\n  ) + (\n    node_memory_Slab{instance=~\"$node_instance\"} or\n    node_memory_Slab_bytes{instance=~\"$node_instance\"}\n  )\n)\n",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (device) (\n  rate(node_network_receive_bytes{instance=~\"$node_instance\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_receive_bytes_total{instance=~\"$node_instance\",device!=\"lo\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (\n  rate(node_network_transmit_bytes{instance=~\"$node_instance\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_transmit_bytes_total{instance=~\"$node_instance\",device!=\"lo\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Network drop rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop{instance=~\"$node_instance\"}[$__rate_interval]) or\nrate(node_network_receive_drop_total{instance=~\"$node_instance\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "rate(node_network_transmit_drop{instance=~\"$node_instance\"}[$__rate_interval]) or\nrate(node_network_transmit_drop_total{instance=~\"$node_instance\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "stat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  ceph_osd_stat_bytes{job=~\"$cluster\", } and\n    on (ceph_daemon, job) ceph_disk_occupation{instance=~\"$node_instance\", job=~\"$cluster\", }\n)\n"
    }
   ]
  },
  {
   "title": "Network error rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs{instance=~\"$node_instance\"}[$__rate_interval]) or\nrate(node_network_receive_errs_total{instance=~\"$node_instance\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "rate(node_network_transmit_errs{instance=~\"$node_instance\"}[$__rate_interval]) or\nrate(node_network_transmit_errs_total{instance=~\"$node_instance\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "OSD Disk Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "$ceph_hosts Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_writes_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$cluster\", instance=~\"$ceph_hosts\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) writes"
    },
    {
     "expr": "(\n  rate(node_disk_reads_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$cluster\", instance=~\"$ceph_hosts\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) reads"
    }
   ]
  },
  {
   "title": "$ceph_hosts Throughput by Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_written_bytes_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$cluster\", instance=~\"$ceph_hosts\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) write"
    },
    {
     "expr": "(\n  rate(node_disk_read_bytes_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$cluster\", instance=~\"$ceph_hosts\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) read"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_writes_completed_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$cluster\", instance=~\"$ceph_hosts\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_io_time_seconds_total{instance=~\"$node_instance\"}[$__rate_interval])\n) * on(device) group_left(ceph_daemon)\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$cluster\", instance=~\"$ceph_hosts\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "Top Slow Ops per Host",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10,\n  (sum by (instance)(ceph_daemon_health_metrics{type=\"SLOW_OPS\", ceph_daemon=~\"osd.*\", job=~\"$cluster\", }))\n)\n"
    }
   ]
  }
 ]
}