{
 "title": "Ceph Object - Sync Overview",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, job)"
   },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_metadata{job=~\"$cluster\", }, ceph_daemon)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replication (throughput) from Source Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_sum{job=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Replication (objects) from Source Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Objects/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_count{job=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Polling Request Latency from Source Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_poll_latency_sum{job=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Object Replications from Source Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_errors{job=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Replication(Time) Delta per shard",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_sync_delta_sync_delta[$__rate_interval])",
     "legendFormat": "{{instance_id}} - {{shard_id}}"
    }
   ]
  }
 ]
}