#ENC[AES256_GCM,data:PpNuYZaDwN4cGbdTQaeq2gcvXSJz9x2GjRecr7KBWEEgzwh1yswW3g71dzUDRuSybGY=,iv:In0nY20FgO8bOPUSgXri1ZUKSNA1xa6i3sDCgnRqDh8=,tag:xoTD9Csrt4stGB/6X/aQ8A==,type:comment]
apiVersion: ENC[AES256_GCM,data:xZs=,iv:l1XYSn5nRcB/2vzGBSo0/LIjLKvlRFZXOQNeCEGffqI=,tag:1LjYK0bEnOBeJssxOgOwPQ==,type:str]
kind: ENC[AES256_GCM,data:PZSF52JJ,iv:wd+j06OFAtIHAWIVOA4VllmseGYc7SvnqPz0GxWIiXI=,tag:3lh0kAWTsgUWFhEO68oahA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iJQap7VkigzMzaaO+rLzyrUanTR7iMo=,iv:0u4ZBAqit4Ial1/9Cf3se9WZIpVPQAbpyrUxSrl95p8=,tag:yJ/wWunSDZsL7jskgGjTpg==,type:str]
    namespace: ENC[AES256_GCM,data:U7yClOT4tEEV,iv:XCpe7bhrxqY5tWCD9VY5ntWQJvCDgALJCsPcAZf8KI4=,tag:otbaqN384IxU9vTIgCbBmg==,type:str]
type: ENC[AES256_GCM,data:MivKQEtf,iv:7VLaaYZhGkEGlBaayWbrnLfXxd+pKXer4Xz3g3SBeVc=,tag:CQZUTuaPPczEW6ItAxSnhg==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:9EE62kbk,iv:KWPm9OqbVl5e9xFxrly07VDQqgywHHvs54b6Gldcavg=,tag:vim4NTSEa41XS0KC5SSLdw==,type:str]
    client-secret: ENC[AES256_GCM,data:MK3QuI8nHOxTVYRHfm8QpC0I0tAu5jxNrU4=,iv:YLzVJQhaSzAuUBRti9B/hTirn3s49Zs8EY11Mk10yDk=,tag:3XRmTSBLAv353fs0z1zY9w==,type:str]
sops:
    age:
        - recipient: age1are2lwem3jtdp3z06xgj5ljvg2xn0rs6yn29x643v3phzkml7clqunt3s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SkdEc2xNTlM1dzFVZlE2
            ZjhVVTdPc1E1SlcrSFFJSmJnN3daNlFha1c4CkFPWWZKdmpsdTJISEVnZGZCNUtY
            MERuc0RLQkxseTVIVlpWb0x5bCs2V0UKLS0tIDM4dkVKdUx4eWhXSm0zNExwZElR
            NVcrMEZ0VlBMS3FHR2ZjWEpCZk1TcVkKxFaQNR77cqaBP1b3rhV7VLR1TWYOMjG9
            tAA6kP9VNxDjL8AHgx0uBrg2ab/Cf68mb0flxeH27SoIX980VcYOHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T10:09:38Z"
    mac: ENC[AES256_GCM,data:u+5Jhj18/n5rhZstsyIr5Om4cge/pxO43W82sbaH02tD7jpYFY7uQLZ+BoSRsS5DvlO5Fh66RFvReBKle9A/Co0D64uklV16ucfuT/1BEoM5fVk5L/3sX4+0x/111hqCUVmPkz67OK1Ed9tTRvuGoiToKB2QJw+sIy5yHz7Ig4Y=,iv:GFJR5A/jmkqV2LVs3VZjfavnbs7YbLr6Ur3cS0QSoQY=,tag:ArzQEgg1xCtmYk/hTEOrEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:nLXttX92oOsT1drlJYuoSPwW+hyBQIYYqaC/KU//UPpOcVMghFEsSFbwqb1DKTJ0sUPdo1Up6iSWe87L9erfxHqPW0U=,iv:2wBSImizKGAd4wOkRnocuMgjNkC0m2O1o29OOGOHMA8=,tag:MD7qbaD2GjHIcYVBWeek6A==,type:comment]
apiVersion: ENC[AES256_GCM,data:r/4=,iv:KXtVBCfXyydRNkf4PEDyovS7UkzdEZY/LB+Ta476gGM=,tag:XptFICwMGfvx4h6IVo2iog==,type:str]
kind: ENC[AES256_GCM,data:NFrta9tl,iv:0qFunPk9GCYO7CWu5H5LW/PYHrjo8juidqd7j3oPzMk=,tag:IkLELATLPQWnLuGfgT9iTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Qb3pflVMi2BiPknMb5VP+va8pnNFY+M=,iv:8RVaCxKpDEl7bRpX57aXCSXqT/EJLKBbp2eb6pmhrP4=,tag:2mlDcObDtlRTFw/4NZ7l7Q==,type:str]
    namespace: ENC[AES256_GCM,data:BPEnYDWw8h8=,iv:J4TjB1Axu/+/YDLrWuKpBP7Cewvfo0mlPE9CVvPJW8Y=,tag:RHvjORcSMz1uCabbyWwwLQ==,type:str]
type: ENC[AES256_GCM,data:Ep1XOQz5,iv:APCItgkGWs4hQnNoAgomRGoe8blREOk/lyqrhkz3FMs=,tag:4+HFyd+2Xi4jppfGVGryLg==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:1PZ9N0F3,iv:6J1baFlhGNYy6PlED4jrIJuli2gOiz+k58PQlN4A3yI=,tag:sghqbZpxa5sNeYillCFRjg==,type:str]
    client-secret: ENC[AES256_GCM,data:fXMTLCgy/RKGHdAPhUBZjuAhKAwkDbqfV44=,iv:hQfv1EfyTx9bJSwRqYery6ATLtSTjjvsTQjdDnp0h7k=,tag:K+bweIBVNfRzVtavgf+N+A==,type:str]
sops:
    age:
        - recipient: age1are2lwem3jtdp3z06xgj5ljvg2xn0rs6yn29x643v3phzkml7clqunt3s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SkdEc2xNTlM1dzFVZlE2
            ZjhVVTdPc1E1SlcrSFFJSmJnN3daNlFha1c4CkFPWWZKdmpsdTJISEVnZGZCNUtY
            MERuc0RLQkxseTVIVlpWb0x5bCs2V0UKLS0tIDM4dkVKdUx4eWhXSm0zNExwZElR
            NVcrMEZ0VlBMS3FHR2ZjWEpCZk1TcVkKxFaQNR77cqaBP1b3rhV7VLR1TWYOMjG9
            tAA6kP9VNxDjL8AHgx0uBrg2ab/Cf68mb0flxeH27SoIX980VcYOHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T10:09:38Z"
    mac: ENC[AES256_GCM,data:u+5Jhj18/n5rhZstsyIr5Om4cge/pxO43W82sbaH02tD7jpYFY7uQLZ+BoSRsS5DvlO5Fh66RFvReBKle9A/Co0D64uklV16ucfuT/1BEoM5fVk5L/3sX4+0x/111hqCUVmPkz67OK1Ed9tTRvuGoiToKB2QJw+sIy5yHz7Ig4Y=,iv:GFJR5A/jmkqV2LVs3VZjfavnbs7YbLr6Ur3cS0QSoQY=,tag:ArzQEgg1xCtmYk/hTEOrEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
