---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-backend-ca
  namespace: kubevirt
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cert-manager-ca-secrets
  target:
    name: keycloak-backend-ca
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ca.crt
      remoteRef:
        key: root-ca-secret
        property: tls.crt
